### ISSUE TITLE
Thread limit flag

### ISSUE THREAD

**Issue by Benjozork** [flybywiresim/igniter#3]
**Why?**

`igniter` currently runs all parallelizable tasks with an unlimited number of worker processes.

Some instrument builds in `a32nx` can consume up to 2GB of memory due to rollup bundling and tree-shaking.

When many (10+ in our case) of those processes exist, CI runners like GitHub Actions can OOM.

**Proposed solution**

Introduce a `-j/--num-workers` flag to limit the number of worker processes in `igniter`. Make sure to wait until <J workers are running to spawn a new worker.

**Comment by tracernz** [comment]
*Job limit. Some of the build tools invoked will start multiple threads/jobs too e.g. cargo.
